{{- if .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  {{- with .Values.frontend.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-frontend
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: reencrypt
  wildcardPolicy: None
{{- end }}
