apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-proxy-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
type: Opaque
{{- if .Values.frontend.oauthProxy.sessionSecret }}
stringData:
  session-secret: {{ .Values.frontend.oauthProxy.sessionSecret | quote }}
{{- else }}
data:
  session-secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
