apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-solr
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: solr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-solr-scc-anyuid
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-solr
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: solr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-solr
    namespace: {{ .Release.Namespace }}
